toma_lecturas/lecturas/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/', views.layout, name='layout'), 
    path('logout/',views.exit,name='exit'),
    path('', views.custom_login, name='login'),
    path('Barrio/indexbarrio',views.indexbarrio,name='indexbarrio'),
    path('Barrio/crearbarrio',views.crearbarrio,name="crearbarrio"),
    path('Barrio/editarbarrio/<int:id>/',views.editarbarrio,name="editarbarrio"),
    path('Barrio/eliminarbarrio/<int:id>/', views.eliminarbarrio, name="eliminarbarrio"),


    path('Micromedidor/indexmicromedidor',views.indexmicromedidor,name='indexmicromedidor'),
    path('Micromedidor/crearmicromedidor',views.crearmicromedidor,name="crearmicromedidor"),
    path('Micromedidor/editarmicromedidor/<int:id>/',views.editarmicromedidor,name="editarmicromedidor"),
    path('Micromedidor/eliminarmicromedidor/<int:id>/',views.eliminarmicromedidor,name="eliminarmicromedidor"),

    
    path('Suscriptor/indexsucriptor',views.indexsuscriptor,name='indexsuscriptor'),
    path('Suscriptor/crearsuscriptor',views.crearsuscriptor,name="crearsuscriptor"),
    path('Suscriptor/editarsuscriptor/<int:id>/',views.editarsuscriptor,name="editarsuscriptor"),
    path('Suscriptor/eliminarsuscriptor/<int:id>/',views.eliminarsuscriptor,name="eliminarsuscriptor"),


    path('SuscriptorMicromedidor/indexsuscriptorMicromedidor',views.indexsuscriptormicromedidor,name='indexsuscriptorMicromedidor') ,
    path('SuscriptorMicromedidor/crearsuscriptormicromedidor',views.crearsuscriptormicromedidor,name="crearsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/editarsuscriptormicromedidor/<int:id>/',views.editarsuscriptormicromedidor,name="editarsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/eliminarsuscriptormicromedidor/<int:id>/',views.eliminarsuscriptormicromedidor,name="eliminarsuscriptormicromedidor"),

    path('Lectura/indexlectura',views.indexlectura,name='indexlectura'),
    path('Lectura/crearlectura',views.crearlectura,name="crearlectura"),
    path('Lectura/editarlectura/<int:id>/',views.editarlectura,name="editarlectura"),
    path('Lectura/eliminarlectura/<int:id>/',views.eliminarlectura,name="eliminarlectura"), 

    path('api/lectura-anterior/<int:suscriptor_id>/', views.obtener_lectura_anterior_api, name='obtener_lectura_anterior_api'),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
   

toma_lecturas/toma_lecturas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lecturas.urls')), 
    
] 

toma_lecturas/lecturas/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver 

class Barrio(models.Model):
    barrio = models.CharField(max_length=20, verbose_name='Nombre del Barrio')
     # Opciones para el campo 'zona'
    OPCIONES_zona= [
        ('zona1', 'Norte'),
        ('zona2', 'Sur occidente'),
        ('zona3', 'En expansion'), 
        
        # Añade más opciones según sea necesario 
    ]

    zona = models.CharField(
        max_length=50,
        choices=OPCIONES_zona,
        verbose_name='zona  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Barrio'
        verbose_name_plural = 'Barrios'

 #eliminar modelo usuario, utilzar clase users de django 

   

class Suscriptor(models.Model):
    primer_nombre = models.CharField(max_length=50, verbose_name='Primer Nombre')
    segundo_nombre = models.CharField(max_length=59, verbose_name='Segundo Nombre')
    primer_apellido = models.CharField(max_length=50, verbose_name='Primer Apellido')
    segundo_apellido = models.CharField(max_length=50, verbose_name='Segundo Apellido')
    barrio = models.ForeignKey(Barrio, on_delete=models.CASCADE, verbose_name='Barrio')
    direccion_IMAGEN = models.ImageField(upload_to='imagenes/', verbose_name='Dirección Imagen')
      # Opciones para el campo 'estrato_socioeconomico'
    OPCIONES_Estrato_social= [
        ('Estrato1', 'Bajo Bajo'),
        ('Estrato2', 'Bajo'),
        ('Estrato3', 'Medio Bajo'), 
        ('Estrato4', 'Medio '), 
        
        # Añade más opciones según sea necesario 
    ]

    Estrato_socioeconomico = models.CharField(
        max_length=50,
        choices=OPCIONES_Estrato_social,
        verbose_name='estrato socioeconimico  ', 
        null=True
    )
     # Opciones para el campo 'uso'
    OPCIONES_Uso= [
        ('Uso1', 'Comercial'),
        ('Uso2', 'Residencial'),
        ('Uso3', 'Oficial'), 
        
        
        # Añade más opciones según sea necesario 
    ]

    Uso = models.CharField(
        max_length=50,
        choices=OPCIONES_Uso,
        verbose_name='Uso  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

class Micromedidor(models.Model):
    nuid = models.CharField(max_length=20, verbose_name='NUID',unique=True) #dejar como unico 
    medidor = models.CharField(max_length=20, verbose_name='Medidor')
    fecha_instalacion = models.DateField(verbose_name='Fecha de Instalación') 
   


    class Meta:
        verbose_name = 'Micromedidor'
        verbose_name_plural = 'Micromedidores'

  

class SuscriptorMicromedidor(models.Model):
    suscriptor = models.ForeignKey(Suscriptor, on_delete=models.CASCADE, verbose_name='Suscriptor')
    micromedidor = models.ForeignKey(Micromedidor, on_delete=models.CASCADE, verbose_name='Micromedidor')

    class Meta:
        verbose_name = 'Relación Suscriptor-Micromedidor'
        verbose_name_plural = 'Relaciones Suscriptor-Micromedidor'



    
class Lectura(models.Model):
    suscriptor_micromedidor = models.ForeignKey(SuscriptorMicromedidor, on_delete=models.CASCADE, verbose_name='Relación Suscriptor-Micromedidor')
    mes_anterior = models.CharField(verbose_name='Mes anterior', max_length=50, blank=True, null=True)
    mes_actual = models.CharField(verbose_name='Mes actual', max_length=50, blank=True, null=True)
    lectura_anterior = models.IntegerField(verbose_name='Lectura anterior', default=0) 
    lectura_actual = models.IntegerField(verbose_name='Lectura actual', default=0) 
    FechaLectura = models.DateTimeField(verbose_name='Fecha de Lectura', auto_now_add=True, editable=False)
    Observaciones = models.CharField(max_length=100, verbose_name='Observaciones', blank=True, null=True)
    OPCIONES_Tipo_lectura = [
        ('tipo1', 'Lectura'),
        ('tipo2', 'Promedio'),
    ]

    tipo_lectura = models.CharField(
        max_length=50,
        choices=OPCIONES_Tipo_lectura,
        verbose_name='Tipo de lectura', 
        null=True
    )
    OPCIONES_estado_micromedidor = [
        ('estado1', 'Bueno'),
        ('estado2', 'Malo'),
    ]

    estado_micromedidor = models.CharField(
        max_length=50,
        choices=OPCIONES_estado_micromedidor,
        verbose_name='Estado del micromedidor',
        null=True
    )
    consumototal = models.IntegerField(verbose_name='Consumo total', default=0) 

    class Meta:
        verbose_name = 'Lectura'
        verbose_name_plural = 'Lecturas'

    def calcular_consumo_total(self):
        if self.lectura_anterior is not None and self.lectura_actual is not None:
            return self.lectura_actual - self.lectura_anterior
        return 0

@receiver(post_save, sender=Lectura)
def actualizar_lectura_anterior(sender, instance, created, **kwargs):
    if created:
        # Obtener la última lectura anterior para el mismo suscriptor y micromedidor
        lectura_anterior = Lectura.objects.filter(
            suscriptor_micromedidor=instance.suscriptor_micromedidor
        ).exclude(id=instance.id).order_by('-FechaLectura').first()

        if lectura_anterior:
            instance.mes_anterior = lectura_anterior.mes_actual
            instance.lectura_anterior = lectura_anterior.lectura_actual
            instance.save() 

toma_lecturas/lecturas/forms.py
from django import forms
from .models import Barrio, Suscriptor, Micromedidor, SuscriptorMicromedidor, Lectura
#####################################################3
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class BarrioForm(forms.ModelForm):
    class Meta:
        model = Barrio
        fields = ['barrio', 'zona']

    def __init__(self, *args, **kwargs):
        super(BarrioForm, self).__init__(*args, **kwargs)

        # Opciones para el campo 'zona'
        self.fields['zona'].widget.choices = Barrio.OPCIONES_zona 




class SuscriptorForm(forms.ModelForm):
    class Meta:
        model = Suscriptor
        fields = ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'barrio', 'direccion_IMAGEN', 'Estrato_socioeconomico', 'Uso']

    def __init__(self, *args, **kwargs):
        super(SuscriptorForm, self).__init__(*args, **kwargs)
        self.fields['Estrato_socioeconomico'].widget.choices = Suscriptor.OPCIONES_Estrato_social
        self.fields['Uso'].widget.choices = Suscriptor.OPCIONES_Uso

        # Filtrar los barrios disponibles para seleccionar en el formulario
        self.fields['barrio'].queryset = Barrio.objects.all()  # Puedes ajustar este queryset según tu lógica de negocio


class MicromedidorForm(forms.ModelForm):
    class Meta:
        model = Micromedidor
        fields = ['nuid', 'medidor', 'fecha_instalacion'] 
    def clean_nuid(self):
        # Obtener el valor ingresado en el campo nuid
        nuid = self.cleaned_data.get('nuid')
        # Verificar si ya existe un Micromedidor con este nuid en la base de datos
        if Micromedidor.objects.filter(nuid=nuid).exists():
            raise forms.ValidationError("El NUID ingresado ya está en uso. Por favor, ingrese un valor único.")
        return nuid 


class SuscriptorMicromedidorForm(forms.ModelForm):
    class Meta:
        model = SuscriptorMicromedidor
        fields = ['suscriptor', 'micromedidor'] 
    def __init__(self, *args, **kwargs):
        super(SuscriptorMicromedidorForm, self).__init__(*args, **kwargs)
        self.fields['suscriptor'].queryset = Suscriptor.objects.all()
        self.fields['micromedidor'].queryset = Micromedidor.objects.all() 


class LecturaForm(forms.ModelForm):
    class Meta:
        model = Lectura
        fields = ['suscriptor_micromedidor', 'lectura_actual','mes_actual','mes_anterior', 'Observaciones', 'tipo_lectura', 'estado_micromedidor'] 

    def __init__(self, *args, **kwargs):
        super(LecturaForm, self).__init__(*args, **kwargs)
        self.fields['tipo_lectura'].widget.choices = Lectura.OPCIONES_Tipo_lectura
        self.fields['estado_micromedidor'].widget.choices = Lectura.OPCIONES_estado_micromedidor
        self.fields['suscriptor_micromedidor'].queryset = SuscriptorMicromedidor.objects.all() 

    def clean_lectura_actual(self):
        lectura_actual = self.cleaned_data['lectura_actual']
        return lectura_actual 
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

toma_lecturas/lecturas/templates/Suscriptor/crear.html
{% extends 'layout.html' %}

{% block titulo %}
CREAR SUSCRIPTOR
{% endblock %}


{% block section %}
<div class="form-container">
 <div class="form-background">
  <div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Crear Suscriptor</h4>
        <p class="card-text">
            <form enctype="multipart/form-data" method="post">
              {% csrf_token %}
              <fieldset>


              <div class="row mb-2">

                  <label class="col-md-4 control-label" for="primer_nombre">Primer nombre</label> 
                  <div class="form-group">
                   <div class="col-md-4">
                     {{ form.primer_nombre }}
                     <div class="help-text">{{ form.primer_nombre.errors }}</div>
                    </div>
                  </div>
                 
                
                <!-- Segundo nombre -->
                
                  <label class="col-md-4 control-label" for="segundo_nombre">Segundo nombre</label>  
                  <div class="form-group">
                   <div class="col-md-4">
                    {{ form.segundo_nombre }}
                    <div class="help-text">{{ form.segundo_nombre.errors }}</div>
                   </div>
                  </div>
                
               
              </div>
                
                <!-- Primer apellido -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="primer_apellido">Primer apellido</label>  
                  <div class="col-md-4">
                    {{ form.primer_apellido }}
                    <div class="help-text">{{ form.primer_apellido.errors }}</div>
                  </div>
                </div>
                
                <!-- Segundo apellido -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="segundo_apellido">Segundo apellido</label>  
                  <div class="col-md-4">
                    {{ form.segundo_apellido }}
                    <div class="help-text">{{ form.segundo_apellido.errors }}</div>
                  </div>
                </div>

                <div class="form-group col-md-6">
                  <label for="direccion_IMAGEN">Imagen</label>
                  {{ form.direccion_IMAGEN }}
                  <div class="help-text">{{ form.direccion_IMAGEN.errors }}</div>
                  
                </div>
              
                <!-- Barrio -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="barrio">Barrio</label>
                    <div class="col-md-4">
                        <select name="{{ form.barrio.name }}" class="form-control">
                            {% for barrio in barrios %}
                            <option value="{{ barrio.pk }}">{{ barrio.barrio }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-12 help-text">{{ form.barrio.errors }}</div>
                    </div>
                </div>

                <!-- Estrato socioeconómico -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="Estrato_socioeconomico">Estrato socioeconómico</label>
                    <div class="col-md-4">
                        <select name="{{ form.Estrato_socioeconomico.name }}" class="form-control">
                            {% for value, label in form.Estrato_socioeconomico.field.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-12 help-text">{{ form.Estrato_socioeconomico.errors }}</div>
                    </div>
                </div>

                <!-- Uso -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="Uso">Uso</label>
                    <div class="col-md-4">
                        <select name="{{ form.Uso.name }}" class="form-control">
                            {% for value, label in form.Uso.field.choices %}
                            <option value="{{ value }}">{{ label }}</option>
                            {% endfor %}
                        </select>
                        <div class="col-12 help-text">{{ form.Uso.errors }}</div>
                    </div>
                </div>

                <input name="" id="" class="btn btn-primary" type="submit" value="Guardar">
             </fieldset>
            </form>
        </p>
    </div>
  </div>
 </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/crearprue.html
<form class="form-horizontal">
    <fieldset>
    
    <!-- Form Name -->
    <legend>Form Name</legend>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_nom1">Primer nombre</label>  
      <div class="col-md-4">
      <input id="text_nom1" name="text_nom1" placeholder="Primer nombre" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_nom2">Segundo nombre</label>  
      <div class="col-md-4">
      <input id="text_nom2" name="text_nom2" placeholder="Segundo nombre" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_ape1">Primer apellido</label>  
      <div class="col-md-4">
      <input id="text_ape1" name="text_ape1" placeholder="Primer apellido" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_ape2">Segundo apellido</label>  
      <div class="col-md-4">
      <input id="text_ape2" name="text_ape2" placeholder="Segundo apellido" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_ciu_nom">Ciudad nombre</label>  
      <div class="col-md-4">
      <input id="text_ciu_nom" name="text_ciu_nom" placeholder="Ciudad nombre" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_dep">Departamento</label>  
      <div class="col-md-4">
      <input id="text_dep" name="text_dep" placeholder="Departamento" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label" for="text_ciu_cod">Ciudad Código</label>  
      <div class="col-md-4">
      <input id="text_ciu_cod" name="text_ciu_cod" placeholder="Ciudad Código" class="form-control input-md" type="text">
    
      </div>
    </div>
    
    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label" for="btn_enviar"></label>
      <div class="col-md-4">
        <button id="btn_enviar" name="btn_enviar" class="btn btn-default">Enviar</button>
      </div>
    </div>
    
    </fieldset>
    </form>

toma_lecturas/lecturas/templates/Suscriptor/editar.html
{% extends 'layout.html' %}
{% block titulo %} Editar Suscriptor {% endblock %}
{% block section %}
<div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Editar Suscriptor</h4>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {% for field in formulario %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {% if field.name == 'barrio' %}
                <select name="{{ field.name }}" class="form-control">
                    {% for barrio in barrios %}
                    <option value="{{ barrio.pk }}">{{ barrio.barrio }}</option>
                    {% endfor %}
                </select>
                {% elif field.name == 'Estrato_socioeconomico' or field.name == 'Uso' %}
                <select name="{{ field.name }}" class="form-control">
                    {% for value, label in field.field.choices %}
                    <option value="{{ value }}">{{ label }}</option>
                    {% endfor %}
                </select>
                {% else %}
                {{ field }}
                {% endif %}
                <div class="col-12 help-text">{{ field.errors }}</div>
            </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary" value="Guardar">
        </form>
    </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/eliminar.html
{% extends 'layout.html' %} {% block titulo %} ELIMINAR BARRIO {% endblock %} {% block section %}
<div class="card text-start">
    <div class="card-body">
        <p class="card-text">
            <h4>¿Estás seguro de que deseas eliminar este suscriptor?</h4> 
            <p>{{ barrio.barrio }}</p>

            <form method="post" action="{% url 'eliminarsuscriptor' suscriptor.id %}"> 
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'indexsuscriptor' %}" class="btn btn-secondary">Cancelar</a> 
            </form>
        </p>
    </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/Suscriptor/form.html
<!-- suscriptor_form.html -->
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
        <label class="form-check-label">{{ field.label }} </label>
        {% if field.name in ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'direccion_IMAGEN'] %}
        {{ field }}
        {% elif field.name == 'barrio' %}
        {{ field }}
        {% elif field.name == 'Estrato_socioeconomico' %}
        <select name="{{ field.name }}" class="form-control">
            {% for value, label in field.field.choices %}
            <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
        </select>
        {% elif field.name == 'Uso' %}
        <select name="{{ field.name }}" class="form-control">
            {% for value, label in field.field.choices %}
            <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
        </select>
        {% endif %}
        <div class="col-12 help-text">{{ field.errors }}</div>
    </div>
    {% endfor %}
    <input name="" id="" class="btn btn-primary" type="submit" value="Guardar">
</form>

toma_lecturas/lecturas/templates/Suscriptor/indexsuscriptor.html
{% extends 'layout.html' %}
{% block titulo %} INDEX SUSCRIPTORES {% endblock %}
{% block section %}
<div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Suscriptores</h4>
        <p class="card-text">
            {% if perms.lecturas.add_suscriptor %}
                <a class="btn btn-success" href="{% url 'crearsuscriptor' %}" role="button">Crear Suscriptor</a>
            {% endif %}
        </p>

        <div class="table-responsive">
            <table id="tablaSuscriptores" class="table table-striped table-borderless table-primary align-middle">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>Primer Nombre</th>
                        <th>Segundo Nombre</th>
                        <th>Primer Apellido</th>
                        <th>Segundo Apellido</th>
                        <th>Barrio</th>
                        <th>Estrato Socioeconómico</th>
                        <th>Uso</th>
                        <th>Imagen</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for suscriptor in suscriptores %}
                    <tr class="table-primary">
                        <td>{{ suscriptor.id }}</td>
                        <td>{{ suscriptor.primer_nombre }}</td>
                        <td>{{ suscriptor.segundo_nombre }}</td>
                        <td>{{ suscriptor.primer_apellido }}</td>
                        <td>{{ suscriptor.segundo_apellido }}</td>
                        <td>{{ suscriptor.barrio.barrio }}</td>
                        <td>{{ suscriptor.get_Estrato_socioeconomico_display }}</td> 
                        <td>{{ suscriptor.get_Uso_display }}</td>
                        <td><img src="{{ suscriptor.direccion_IMAGEN.url }}" height="100"></td> <!-- Muestra la imagen -->
                        <td>
                            <a class="btn btn-primary" href="{% url 'editarsuscriptor' suscriptor.id %}" role="button">Editar</a>
                            {% if perms.lecturas.delete_suscriptor %}
                                <a id="eliminar_{{ suscriptor.id }}" class="btn btn-danger" href="#" role="button">Eliminar</a>
                            {% endif %}
                        </td>
                    </tr>
                    <script>
                        document.getElementById('eliminar_{{ suscriptor.id }}').addEventListener('click', function() {
                            if (confirm('¿Estás seguro de que deseas eliminar este suscriptor?')) {
                                window.location.href = "{% url 'eliminarsuscriptor' suscriptor.id %}";
                            }
                        });
                    </script>
                    {% endfor %}
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>

<!-- Agrega las referencias y el script de DataTables -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

<script>
    // Inicializa la tabla con DataTables
    $(document).ready(function() {
        $('#tablaSuscriptores').DataTable();
    });
</script>

{% endblock %}