toma_lecturas/lecturas/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/', views.layout, name='layout'), 
    path('logout/',views.exit,name='exit'),
    path('', views.custom_login, name='login'),
    path('Barrio/indexbarrio',views.indexbarrio,name='indexbarrio'),
    path('Barrio/crearbarrio',views.crearbarrio,name="crearbarrio"),
    path('Barrio/editarbarrio/<int:id>/',views.editarbarrio,name="editarbarrio"),
    path('Barrio/eliminarbarrio/<int:id>/', views.eliminarbarrio, name="eliminarbarrio"),


    path('Micromedidor/indexmicromedidor',views.indexmicromedidor,name='indexmicromedidor'),
    path('Micromedidor/crearmicromedidor',views.crearmicromedidor,name="crearmicromedidor"),
    path('Micromedidor/editarmicromedidor/<int:id>/',views.editarmicromedidor,name="editarmicromedidor"),
    path('Micromedidor/eliminarmicromedidor/<int:id>/',views.eliminarmicromedidor,name="eliminarmicromedidor"),

    
    path('Suscriptor/indexsucriptor',views.indexsuscriptor,name='indexsuscriptor'),
    path('Suscriptor/crearsuscriptor',views.crearsuscriptor,name="crearsuscriptor"),
    path('Suscriptor/editarsuscriptor/<int:id>/',views.editarsuscriptor,name="editarsuscriptor"),
    path('Suscriptor/eliminarsuscriptor/<int:id>/',views.eliminarsuscriptor,name="eliminarsuscriptor"),


    path('SuscriptorMicromedidor/indexsuscriptorMicromedidor',views.indexsuscriptormicromedidor,name='indexsuscriptorMicromedidor') ,
    path('SuscriptorMicromedidor/crearsuscriptormicromedidor',views.crearsuscriptormicromedidor,name="crearsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/editarsuscriptormicromedidor/<int:id>/',views.editarsuscriptormicromedidor,name="editarsuscriptormicromedidor"),
    path('SuscriptorMicromedidor/eliminarsuscriptormicromedidor/<int:id>/',views.eliminarsuscriptormicromedidor,name="eliminarsuscriptormicromedidor"),

    path('Lectura/indexlectura',views.indexlectura,name='indexlectura'),
    path('Lectura/crearlectura',views.crearlectura,name="crearlectura"),
    path('Lectura/editarlectura/<int:id>/',views.editarlectura,name="editarlectura"),
    path('Lectura/eliminarlectura/<int:id>/',views.eliminarlectura,name="eliminarlectura"), 

    path('api/lectura-anterior/<int:suscriptor_id>/', views.obtener_lectura_anterior_api, name='obtener_lectura_anterior_api'),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
   

toma_lecturas/toma_lecturas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lecturas.urls')), 
    
] 

toma_lecturas/lecturas/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver 

class Barrio(models.Model):
    barrio = models.CharField(max_length=20, verbose_name='Nombre del Barrio')
     # Opciones para el campo 'zona'
    OPCIONES_zona= [
        ('zona1', 'Norte'),
        ('zona2', 'Sur occidente'),
        ('zona3', 'En expansion'), 
        
        # Añade más opciones según sea necesario 
    ]

    zona = models.CharField(
        max_length=50,
        choices=OPCIONES_zona,
        verbose_name='zona  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Barrio'
        verbose_name_plural = 'Barrios'

 #eliminar modelo usuario, utilzar clase users de django 

   

class Suscriptor(models.Model):
    primer_nombre = models.CharField(max_length=50, verbose_name='Primer Nombre')
    segundo_nombre = models.CharField(max_length=59, verbose_name='Segundo Nombre')
    primer_apellido = models.CharField(max_length=50, verbose_name='Primer Apellido')
    segundo_apellido = models.CharField(max_length=50, verbose_name='Segundo Apellido')
    barrio = models.ForeignKey(Barrio, on_delete=models.CASCADE, verbose_name='Barrio')
    direccion_IMAGEN = models.ImageField(upload_to='imagenes/', verbose_name='Dirección Imagen')
      # Opciones para el campo 'estrato_socioeconomico'
    OPCIONES_Estrato_social= [
        ('Estrato1', 'Bajo Bajo'),
        ('Estrato2', 'Bajo'),
        ('Estrato3', 'Medio Bajo'), 
        ('Estrato4', 'Medio '), 
        
        # Añade más opciones según sea necesario 
    ]

    Estrato_socioeconomico = models.CharField(
        max_length=50,
        choices=OPCIONES_Estrato_social,
        verbose_name='estrato socioeconimico  ', 
        null=True
    )
     # Opciones para el campo 'uso'
    OPCIONES_Uso= [
        ('Uso1', 'Comercial'),
        ('Uso2', 'Residencial'),
        ('Uso3', 'Oficial'), 
        
        
        # Añade más opciones según sea necesario 
    ]

    Uso = models.CharField(
        max_length=50,
        choices=OPCIONES_Uso,
        verbose_name='Uso  ', 
        null=True
    )

    class Meta:
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'

class Micromedidor(models.Model):
    nuid = models.CharField(max_length=20, verbose_name='NUID',unique=True) #dejar como unico 
    medidor = models.CharField(max_length=20, verbose_name='Medidor')
    fecha_instalacion = models.DateField(verbose_name='Fecha de Instalación') 
   


    class Meta:
        verbose_name = 'Micromedidor'
        verbose_name_plural = 'Micromedidores'

  

class SuscriptorMicromedidor(models.Model):
    suscriptor = models.ForeignKey(Suscriptor, on_delete=models.CASCADE, verbose_name='Suscriptor')
    micromedidor = models.ForeignKey(Micromedidor, on_delete=models.CASCADE, verbose_name='Micromedidor')

    class Meta:
        verbose_name = 'Relación Suscriptor-Micromedidor'
        verbose_name_plural = 'Relaciones Suscriptor-Micromedidor'



    
class Lectura(models.Model):
    suscriptor_micromedidor = models.ForeignKey(SuscriptorMicromedidor, on_delete=models.CASCADE, verbose_name='Relación Suscriptor-Micromedidor')
    mes_anterior = models.CharField(verbose_name='Mes anterior', max_length=50, blank=True, null=True)
    mes_actual = models.CharField(verbose_name='Mes actual', max_length=50, blank=True, null=True)
    lectura_anterior = models.IntegerField(verbose_name='Lectura anterior', default=0) 
    lectura_actual = models.IntegerField(verbose_name='Lectura actual', default=0) 
    FechaLectura = models.DateTimeField(verbose_name='Fecha de Lectura', auto_now_add=True, editable=False)
    Observaciones = models.CharField(max_length=100, verbose_name='Observaciones', blank=True, null=True)
    OPCIONES_Tipo_lectura = [
        ('tipo1', 'Lectura'),
        ('tipo2', 'Promedio'),
    ]

    tipo_lectura = models.CharField(
        max_length=50,
        choices=OPCIONES_Tipo_lectura,
        verbose_name='Tipo de lectura', 
        null=True
    )
    OPCIONES_estado_micromedidor = [
        ('estado1', 'Bueno'),
        ('estado2', 'Malo'),
    ]

    estado_micromedidor = models.CharField(
        max_length=50,
        choices=OPCIONES_estado_micromedidor,
        verbose_name='Estado del micromedidor',
        null=True
    )
    consumototal = models.IntegerField(verbose_name='Consumo total', default=0) 

    class Meta:
        verbose_name = 'Lectura'
        verbose_name_plural = 'Lecturas'

    def calcular_consumo_total(self):
        if self.lectura_anterior is not None and self.lectura_actual is not None:
            return self.lectura_actual - self.lectura_anterior
        return 0

@receiver(post_save, sender=Lectura)
def actualizar_lectura_anterior(sender, instance, created, **kwargs):
    if created:
        # Obtener la última lectura anterior para el mismo suscriptor y micromedidor
        lectura_anterior = Lectura.objects.filter(
            suscriptor_micromedidor=instance.suscriptor_micromedidor
        ).exclude(id=instance.id).order_by('-FechaLectura').first()

        if lectura_anterior:
            instance.mes_anterior = lectura_anterior.mes_actual
            instance.lectura_anterior = lectura_anterior.lectura_actual
            instance.save() 

toma_lecturas/lecturas/forms.py
from django import forms
from .models import Barrio, Suscriptor, Micromedidor, SuscriptorMicromedidor, Lectura
#####################################################3
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class BarrioForm(forms.ModelForm):
    class Meta:
        model = Barrio
        fields = ['barrio', 'zona']

    def __init__(self, *args, **kwargs):
        super(BarrioForm, self).__init__(*args, **kwargs)

        # Opciones para el campo 'zona'
        self.fields['zona'].widget.choices = Barrio.OPCIONES_zona 




class SuscriptorForm(forms.ModelForm):
    class Meta:
        model = Suscriptor
        fields = ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'barrio', 'direccion_IMAGEN', 'Estrato_socioeconomico', 'Uso']

    def __init__(self, *args, **kwargs):
        super(SuscriptorForm, self).__init__(*args, **kwargs)
        self.fields['Estrato_socioeconomico'].widget.choices = Suscriptor.OPCIONES_Estrato_social
        self.fields['Uso'].widget.choices = Suscriptor.OPCIONES_Uso

        # Filtrar los barrios disponibles para seleccionar en el formulario
        self.fields['barrio'].queryset = Barrio.objects.all()  # Puedes ajustar este queryset según tu lógica de negocio


class MicromedidorForm(forms.ModelForm):
    class Meta:
        model = Micromedidor
        fields = ['nuid', 'medidor', 'fecha_instalacion'] 
    def clean_nuid(self):
        # Obtener el valor ingresado en el campo nuid
        nuid = self.cleaned_data.get('nuid')
        # Verificar si ya existe un Micromedidor con este nuid en la base de datos
        if Micromedidor.objects.filter(nuid=nuid).exists():
            raise forms.ValidationError("El NUID ingresado ya está en uso. Por favor, ingrese un valor único.")
        return nuid 


class SuscriptorMicromedidorForm(forms.ModelForm):
    class Meta:
        model = SuscriptorMicromedidor
        fields = ['suscriptor', 'micromedidor'] 
    def __init__(self, *args, **kwargs):
        super(SuscriptorMicromedidorForm, self).__init__(*args, **kwargs)
        self.fields['suscriptor'].queryset = Suscriptor.objects.all()
        self.fields['micromedidor'].queryset = Micromedidor.objects.all() 


class LecturaForm(forms.ModelForm):
    class Meta:
        model = Lectura
        fields = ['suscriptor_micromedidor', 'lectura_actual','mes_actual','mes_anterior', 'Observaciones', 'tipo_lectura', 'estado_micromedidor'] 

    def __init__(self, *args, **kwargs):
        super(LecturaForm, self).__init__(*args, **kwargs)
        self.fields['tipo_lectura'].widget.choices = Lectura.OPCIONES_Tipo_lectura
        self.fields['estado_micromedidor'].widget.choices = Lectura.OPCIONES_estado_micromedidor
        self.fields['suscriptor_micromedidor'].queryset = SuscriptorMicromedidor.objects.all() 

    def clean_lectura_actual(self):
        lectura_actual = self.cleaned_data['lectura_actual']
        return lectura_actual 
        
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

toma_lecturas/lecturas/templates/SuscriptorMicromedidor/crear.html
{% extends 'layout.html' %}

{% block titulo %} CREAR SUSCRIPTOR DE MICROMEDIDOR {% endblock %}

{% block section %}
<div class="form-container">
 <div class="form-background">
   <div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Crear Suscriptor de Micromedidor</h4>
        <div class="mb-3">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="col-md-4">
                    <div class="form-group">
                     <label class="form-label">Suscriptor:</label>
                     <select name="suscriptor" class="form-control">
                        {% for suscriptor in suscriptores %}
                            <option value="{{ suscriptor.id }}">{{ suscriptor.primer_nombre }} {{suscriptor.segundo_nombre}} {{suscriptor.primer_apellido}}</option>
                        {% endfor %}
                     </select>
                    <div>
                </div>
                <div class="mb-3">
                    <label class="form-label">Micromedidor:</label>
                    <select name="micromedidor" class="form-control">
                        {% for micromedidor in micromedidores %}
                            <option value="{{ micromedidor.id }}">{{ micromedidor.medidor }}</option> 
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
   </div>
 </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/SuscriptorMicromedidor/editar.html
<!-- editar_suscriptor_micromedidor.html -->

{% extends 'layout.html' %}
{% block titulo %} EDITAR SUSCRIPTOR DE MICROMEDIDOR {% endblock %}
{% block section %}
<div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Editar Suscriptor de Micromedidor</h4>
        <div class="mb-3">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Suscriptor:</label>
                    <select name="suscriptor" class="form-control">
                        {% for suscriptor in suscriptores %}
                            <option value="{{ suscriptor.id }}" {% if suscriptor.id == form.instance.suscriptor.id %} selected {% endif %}>{{ suscriptor.primer_nombre }} {{suscriptor.segundo_nombre}}</option>
                        {% endfor %}
                    </select> 
                </div>
                <div class="mb-3">
                    <label class="form-label">Micromedidor:</label>
                    <select name="micromedidor" class="form-control">
                        {% for micromedidor in micromedidores %}
                            <option value="{{ micromedidor.id }}" {% if micromedidor.id == form.instance.micromedidor.id %} selected {% endif %}>{{ micromedidor.medidor }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

toma_lecturas/lecturas/templates/SuscriptorMicromedidor/eliminar.html
{% extends 'layout.html' %} {% block titulo %} ELIMINAR SUSCRIPTOR DE MICROMEDIDOR {% endblock %} {% block section %}
<div class="card text-start">
    <div class="card-body">
        <p class="card-text">
            <h4>¿Estás seguro de que deseas eliminar este suscriptor asociado a este micromedidor?</h4> 
            <p>{{ barrio.barrio }}</p>

            <form method="post" action="{% url 'eliminarsuscriptormicromedidor' suscriptor_micromedidor.id %}"> 
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'indexsuscriptorMicromedidor' %}" class="btn btn-secondary">Cancelar</a> 
            </form>
        </p>
    </div>
</div>
{% endblock %} 

toma_lecturas/lecturas/templates/SuscriptorMicromedidor/form.html
<!-- suscriptormicromedidor_form.html -->
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-3">
        <label class="form-check-label">{{ field.label }} </label>
        {{ field }}
        <div class="col-12 help-text">{{ field.errors }}</div>
    </div>
    {% endfor %}
    <input name="" id="" class="btn btn-primary" type="submit" value="Guardar">
</form>

toma_lecturas/lecturas/templates/SuscriptorMicromedidor/indexsuscriptorMicromedidor.html
{% extends 'layout.html' %}
{% block titulo %} INDEX SUSCRIPTORES DE MICROMEDIDORES {% endblock %}
{% block section %}
<div class="card text-start">
    <div class="card-body">
        <h4 class="card-title">Suscriptores de Micromedidores</h4>
        <p class="card-text">
            {% if perms.lecturas.add_suscriptormicromedidor %}
                <a class="btn btn-success" href="{% url 'crearsuscriptormicromedidor' %}" role="button">Crear Suscriptor de Micromedidor</a>
            {% endif %}
        </p>

        <div class="table-responsive"> 
            <table id="tablaSuscriptoresMicromedidores" class="table table-striped table-borderless table-primary align-middle">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>Suscriptor</th>
                        <th>Micromedidor</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for suscriptor_micromedidor in suscriptormicromedidor %}
                    <tr class="table-primary">
                        <td>{{ suscriptor_micromedidor.id }}</td>

                        <td><a href="#">{{ suscriptor_micromedidor.suscriptor.primer_nombre }} {{ suscriptor_micromedidor.suscriptor.segundo_nombre }} {{ suscriptor_micromedidor.suscriptor.primer_apellido }}</a>   </td>
                        <td>{{ suscriptor_micromedidor.micromedidor.medidor }}</td>
                        <td>
                            <a class="btn btn-primary" href="{% url 'editarsuscriptormicromedidor' suscriptor_micromedidor.id %}" role="button">Editar</a>
                            {% if perms.lecturas.delete_suscriptormicromedidor %}
                                <a id="eliminar_{{ suscriptor_micromedidor.id }}" class="btn btn-danger" href="{% url 'eliminarsuscriptormicromedidor' suscriptor_micromedidor.id %}" role="button">Eliminar</a>
                            {% endif %}
                        </td>
                    </tr>
                    <script>
                        document.getElementById('eliminar_{{ suscriptor_micromedidor.id }}').addEventListener('click', function() {
                            if (confirm('¿Estás seguro de que deseas eliminar este suscriptor de micromedidor?')) {
                                window.location.href = "{% url 'eliminarsuscriptormicromedidor' suscriptor_micromedidor.id %}"; 
                            }
                        });
                    </script>
                    {% endfor %} 
                </tbody>
                <tfoot></tfoot>
            </table>
        </div>
    </div>
</div>

<!-- Agrega las referencias y el script de DataTables -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

<script>
    // Inicializa la tabla con DataTables
    $(document).ready(function() {
        $('#tablaSuscriptoresMicromedidores').DataTable();
    });
</script>

{% endblock %}